version: 2
updates:
  # Ruby dependencies in back/
  - package-ecosystem: "bundler"
    directory: "/back"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # npm dependencies in front/
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5