services:
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./front:/app
    command: yarn dev -p 4000
    ports:
      - "4000:4000"
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
      RAILS_LOG_TO_STDOUT: "true"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' -p 3000"
    volumes:
      - ./back:/app
    depends_on:
      - db
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: