FROM ruby:3.2.2

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install -y build-essential nodejs postgresql-client

# バンドラー関連のディレクトリ作成と権限設定
RUN mkdir -p /usr/local/bundle && \
    chmod -R 777 /usr/local/bundle && \
    mkdir -p /.bundle && \
    chmod -R 777 /.bundle

# Gemfileコピー、インストール
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN gem install bundler
RUN bundle install

COPY . /app

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0", "-p", "3000"]