FROM node:20.18.1-slim

# 作業ディレクトリを設定
WORKDIR /app

# 環境変数の設定
ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo

# pnpmのインストール
RUN npm install -g pnpm

# アプリケーションの依存関係をコピー
COPY package.json pnpm-lock.yaml ./

# 依存関係のインストール
RUN pnpm install

# アプリケーションのソースコードをコピー
COPY . .

# 開発サーバーを起動
EXPOSE 3000
CMD ["pnpm", "dev"]